services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - CHALLENGE_HOST=127.0.0.1
      - SATELLITE_TOKEN=fake_token
    restart: unless-stopped
    network_mode: host

  satellite:
    build:
      context: ./satellite
      dockerfile: Dockerfile
    environment:
      - SATELLITE_TOKEN=fake_token
    restart: unless-stopped
    network_mode: host

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    environment:
      - SATELLITE_HOST=127.0.0.1
      - SATELLITE_PORT=8000
      - FRONTEND_HOST=127.0.0.1
      - FRONTEND_PORT=5000
    depends_on:
      - frontend
      - satellite
    network_mode: host
